### ISSUE TITLE
Why use CALC_MEASURED_SKEW and not use SKEW_PROFILE_SAVE?

### ISSUE THREAD

**Issue by VooDisss** [dirtdigger/fleur_de_cali#4]
![image](https://github.com/dirtdigger/fleur_de_cali/assets/41582720/99dbf2ae-fb8d-447c-b514-233a01b66590)

**Comment by VooDisss** [comment]
I think CALC_MEASURED_SKEW is useless, because it only shows the same value as in "helper" tab in spreadsheet. Also it does not save the profile to persistent memory.

**Comment by dirtdigger** [comment]
CALC_MEASURED_SKEW was an earlier quick suggestion from fenrir on Printables. 

This is what the next version will look like:
![image](https://github.com/dirtdigger/fleur_de_cali/assets/11851803/8ed498eb-1845-4581-996e-29a25fc5f3e0)

**Comment by dirtdigger** [comment]
Suggestion planned.

**Comment by VooDisss** [comment]
Please also add `SKEW_PROFILE SAVE=my_skew_profile` . Because otherwise the SET_SKEW command value will not remain in the printer.cfg on the next start, and this can lead to many misunderstandings on newbies I think.
