### ISSUE TITLE
Radioactive calistar is/seems missing here

### ISSUE THREAD

**Issue by ProBackup-nl** [dirtdigger/fleur_de_cali#7]
The printables.com model downloads also has a radioactive shaped version.

That radioactive calistar variant, seems missing here.

![Radioactive calistar by Printics](https://github.com/dirtdigger/fleur_de_cali/assets/515451/bab8c0f1-9687-4cc3-8492-60813e3c8118)

**Comment by dirtdigger** [comment]
This is in a separate branch currently [link](https://github.com/dirtdigger/fleur_de_cali/tree/radioactive_calistar)
